services:
  mikaboshi-server:
    container_name: mikaboshi-server
    image: arianpg/mikaboshi-server:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - GRPC_PORT=50051
      - HTTP_PORT=8080
      #- PEER_TIMEOUT=30
      #- CHANNEL_CAPACITY=1000
      #- GEOIP_PATH=/data/geoip.mmdb
      #- BASIC_AUTH_USER=admin
      #- BASIC_AUTH_PASSWORD=admin
    volumes:
      # Mount the local geoip.mmdb file to the container
      # Please place your geoip.mmdb file in the same directory as this compose.yml
      #- ./geoip.mmdb:/data/geoip.mmdb:ro
